### ISSUE TITLE
Multiplayer Lobby Page

### ISSUE THREAD

**Issue by nekoraw** [nekoraw/guweb#12]
**Describe alternatives you've considered**
there's an api endpoint on nekoraw/bancho.py that returns multiplayer data -> `https://api.{domain}/v1/get_match?id={match_id}`

there are some sample data you can get: match id 20 to 24
https://api.takuji.nkrw.dev/v1/get_match?id=20

**Comment by luis10barbo** [comment]
This api route should give some sort of "match_name", like the official osu! one, but it doesnt. Is this fixable?

**Comment by luis10barbo** [comment]
+ Scores "max_combo" are missing in api response
![image](https://github.com/nekoraw/guweb/assets/89195562/905fad7e-9aa1-4d0d-9fe7-18728d955731)

**Comment by nekoraw** [comment]
yeah will fix it soon, i will need to modify the database schema

for now just assume these fields exists in the json
