### ISSUE TITLE
Broken foreigner sorting at global leaderboard

### ISSUE THREAD

**Issue by luis10barbo** [nekoraw/guweb#16]
**Describe the bug**
At global leaderboards page, foreigner users sorting is "ZZ" not "XX"

**To reproduce**
1. Go to 'https://takuji.nkrw.dev/leaderboard'
2. Sort by "Estrangeiro"
4. See error, which is a blank page, not showing any foreigner users

**Expected behavior**
Show all foreigner users in page.

**Screenshots**
![image](https://github.com/nekoraw/guweb/assets/89195562/ac369bfc-df7e-4905-bb27-3990bbd93cfb)

**Comment by nekoraw** [comment]
I've changed the foreigner country to xx to represent the unidentified country code as [defined here](https://en.m.wikipedia.org/wiki/ISO_3166-1_alpha-2#XX)

this should work fine
https://takuji.nkrw.dev/leaderboard/std/pp/vn/XX

I think we just need to change the option value on the dropdown menu for it to work correctly
